name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image with tags
      run: |
        IMAGE_NAME=ghcr.io/walzen-group/microsoft-rewards-script
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$(date +%s)

    - name: Push Docker image
      run: |
        IMAGE_NAME=ghcr.io/walzen-group/microsoft-rewards-script
        docker push $IMAGE_NAME:latest
